package example:parser@0.1.0;

interface parsing {
    use example:types/types@0.1.0.{ast};

    /// Parse the source of a module into an AST
    parse: func(source: string) -> ast;
}

world parser {
    export parsing;
}
